name: Build and Deploy Frontend and Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy frontend to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'testappdevops'
          package: ./frontend/build

      - name: Install dependencies and build backend
        run: |
          cd backend
          npm install

      - name: Deploy backend to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'testappdevops'
          package: ./backend
